// JavaScript Document

	function ConfirmExit() {
		document.getElementById("Outer2").style.display = "block"
		document.getElementById("Outer").style.display = "none";
		document.getElementById("Outer4").style.display = "none";
		document.getElementById("Outer3").style.display = "none";;
		MSApp.terminateApp();
	/*	alert('backbutton');*/
		 }

function todaysDate() {
var d = new Date();
document.getElementById("demo").innerHTML = d.toDateString();
}

function myFunction() {
	document.getElementById('Outer').style.display = 'none';
	document.getElementById('Outer2').style.display = 'block';
	document.getElementById('Outer3').style.display = 'none';
	document.getElementById('Outer4').style.display = 'none';
	document.getElementById('Texty').innerHTML='Today\'s Quote';		
/*var now = new Date();
var start = new Date(now.getFullYear(), 0, 0);
var diff = now - start;
var oneDay = 1000 * 60 * 60 * 24;
var day = Math.floor(diff / oneDay);
alert(day);*/

}

function backFunction(){
if (select==1) {
  // alert("came from homepage");
   document.getElementById('Outer2').style.display = 'block';document.getElementById('Outer3').style.display = 'none';document.getElementById('Outer4').style.display = 'none'; document.getElementById('Outer').style.display = 'none';
} else {
    //alert("came from quotespage");
	  document.getElementById('Outer').style.display = 'block';document.getElementById('Outer3').style.display = 'none';document.getElementById('Outer4').style.display = 'none'; document.getElementById('Outer2').style.display = 'none';
}
}
//var Texty = document.getElementById("textDiv");
var select = 1;
var now = new Date();
var start = new Date(now.getFullYear(), 0, 0);
var diff = now - start;
var oneDay = 1000 * 60 * 60 * 24;
var day = Math.floor(diff / oneDay);
var car=[];
car[0]="\"The idea that you can’t lose contact with the leaders has cut more throats than it has saved.\"<br><br><div class=\"SigText\">- Arthur Lydiard</div>";
car[1]="Happy New Year! Now get off that couch and get outside running to work off all that festive excess!";
car[2]="\"The decathlon is nine Mickey Mouse events and the 1500 metres.\"<br><br><div class=\"SigText\">- Steve Ovett</div>";
car[3]="Joke quote:<br><br>\"Running is great, cause you forget all your problems because you’re too busy focusing on one problem, and that’s that your whole body hurts.\"";
car[4]="\"When using the run-walk method to finish a marathon, the most important walk break comes in the first mile. The second most important one comes in the second mile, and so on. The point is, walk before you become fatigued.\"<br><br><div class=\"SigText\">- Jeff Galloway</div>";
car[5]="Life is better when you’re running.";
car[6]="Sky above me, earth below me... FIRE WITHIN ME!";
car[7]="\"We run to undo the damage we’ve done to body and spirit. We run to find some part of ourselves yet undiscovered.\"<br><br><div class=\"SigText\">- John \"The Penguin\" Bingham</div>";
car[8]="\"Just remember this: Nobody ever won the olive wreath with an impressive training diary.\"<br><br><div class=\"SigText\">- Marty Liquori</div>";
car[9]="A short run is better than no run at all.";
car[10]="\"The true runner is a very fortunate person. He has found something in him that is just perfect.\"<br><br><div class=\"SigText\">- George Sheehan</div>";
car[11]="\"Children run everywhere for a reason - it’s fun. Grown-ups can forget that sometimes.\"<br><br><div class=\"SigText\">- Jim Butcher, Dead Beat</div>";
car[12]="Repair your muscles: Eat 20g of protein soon after a run to kick start muscle repair.";
car[13]="\"As your training moves from base training to more intense work, to tapering, your nutrition needs to change.\"<br><br><div class=\"SigText\">- Charlotte Campbell, Triathlon for Women: Everything you need to know to get started and succeed</div>";
car[14]="\"I make sure I have some really enjoyable training runs, remembering to ‘smell the roses’ along the way. That way I don’t become caught up in the training-is-everything syndrome.\"<div class=\"SigText\">- Sue Stricklin</div>";
car[15]="\"People always ask why I do it. I’m wondering why they don’t?\"";
car[16]="You don’t have to go fast. You just have to go.";
car[17]="After you finish your run, do a three to five minute cool down run, and then stretch thoroughly.";
car[18]="\"Squinting intently requires more energy than you can spare over 26.2 miles. So if it’s sunny or you’re allergic to dust or pollen, wear sunglasses.\"<br><br><div class=\"SigText\">- Kim Jones, world-class masters marathoner</div>";
car[19]="\"Body follows mind. If the mind compares itself to others this could lead to overtraining. Tune out what other runners do and how fast they run. Tune in, instead, to how your body wants to increase speed and distance.\"<br><br><div class=\"SigText\">- Gina Greenlee, The Whole Person Guide to Your First Marathon: A Mind Body Spirit Companion</div>";
car[20]="\"Move into a hill session gradually, running the first few repeats moderately and increasing the effort as you go along.\"<br><br><div class=\"SigText\">- Frank Shorter, 1972 Olympic Marathon Champion</div>";
car[21]="\"The miracle isn’t that I finished. The miracle is that I had the courage to start.\"<br><br><div class=\"SigText\">- John Bingham, No Need for Speed: A Beginner’s Guide to the Joy of Running</div>";
car[22]="Joke:<br><br>Q: What do you get when you run in front of a car?<br><br>A: Tired.";
car[23]="I don’t always love running. But I love having run.";
car[24]="\"Is beer good for runners? Sure...if it’s the other guy drinking it.\"<br><br><div class=\"SigText\">- Jim Fixx, author of the running bestseller, The Complete Book of Running</div>";
car[25]="\"Get off the couch to get back in the game.\"<br><br><div class=\"SigText\">- Toni Sorenson</div>";
car[26]="\"Worrying gets you nowhere. if you turn up worrying about how you’re going to perform, you’ve already lost. Train hard, turn up, run your best and the rest will take care of itself.\"<br><br><div class=\"SigText\">- Usain Bolt</div>";
car[27]="\"He was onto something. Something huge. It wasn’t just how to run; it was how to live, the essence of who we are as a species and what we’re meant to be.\"<div class=\"SigText\">- Christopher McDougall</div>";
car[28]="\"If you put down a good solid foundation, you can then build one room after another and pretty soon you have a house. After your base mileage, add hills, pace work, speedwork, and finally race strategy.\"<br><br><div class=\"SigText\">- Rod Dixon, New Zealand Olympian and 1983 New York City Marathon champ</div>";
car[29]="\"Feather-light racing flats might help you run a faster 5k, but lightweight performance trainers (with better protection and cushioning) are a better choice for most runners, especially in longer races.\"<br><br><div class=\"SigText\">- Bob Wischnia and Paul Carrozza, Runner’s World shoe experts</div>";
car[30]="\"If you feel like eating, eat. Let your body tell you what it wants.\"<br><br><div class=\"SigText\">- Joan Samuelson, 1984 Olympic marathon champion</div>";
car[31]="Runners logic: I’m tired, I think I’ll go for a run.";
car[32]="\"Somebody may beat me, but they are going to have to bleed to do it.\"<br><br><div class=\"SigText\">- Steve Prefontaine</div>";
car[33]="\"A 40-minute run punctuated with a half-dozen 30-second pace pickups (not all-out sprints) can really jazz up an otherwise boring training run.\"<br><br><div class=\"SigText\">- Amby Burfoot, Runner’s World editor and 1968 Boston Marathon champ</div>";
car[34]="Beginners Tip: Get good (non-cotton) socks. Cotton socks soak up and hang on to moisture, socks made from a synthetic material will wick moisture away from your feet and control temperature well, which means a much less swampy run.";
car[35]="Joke:<br><br>My therapist told me I have to quit running and drinking, I laughed and told her, \"Maybe you’re the crazy one.\"";
car[36]="\"As we run, we become.\"<br><br><div class=\"SigText\">- Amby Burfoot</div>";
car[37]="\"Running is real and relatively simple... but it ain’t easy.\"<br><br><div class=\"SigText\">- Mark Will-Weber</div>";
car[38]="\"You must listen to your body. Run through annoyance, but not through pain.\"<br><br><div class=\"SigText\">- Dr. George Sheehan</div>";
car[39]="\"Hydrate. Hydrate. Hydrate! In cold weather and warm. We use water to sweat, lubricate joints, tendons, and ligaments, and to carry blood efficiently to major organs. I work all day at hydrating.\"<br><br><div class=\"SigText\">- Dr. Alex Ratelle, former masters running great</div>";
car[40]="\"Once you find a warmup routine that works, repeat it as habitually as possible.\"<br><br><div class=\"SigText\">- Ted Corbitt</div>";
car[41]="\"Throw away your 10-function chronometer, heart-rate monitor with the computer printout, training log, high-tech underwear, pace charts, and laboratory-rat-tested-air-injected-gel-lined-motion-control-top-of-the-line footwear... run with your own imagination.\"<br><br><div class=\"SigText\">- Lorraine Moller, 1992 Olympic marathon bronze medalist</div>";
car[42]="\"Running hills breaks up your rhythm and forces your muscles to adapt to new stresses. The result? You become stronger.\"<br><br><div class=\"SigText\">- Eamonn Coghlan, Irish Olympian and only 40-year-old to break 4 minutes in the mile</div>";
car[43]="Your lungs are burning, your legs are shredded, you heart is pounding, KEEP GOING!";
car[44]="Studies have shown that muscles are most receptive to rebuilding glycogen stores within the first 30 minutes after exercise. If you eat soon after your long run or intense workout, you can minimize muscle stiffness and soreness.";
car[45]="\"Don’t attack a hill from the very bottom - it’s bigger than you are!\"<br><br><div class=\"SigText\">- Harry Groves, renowned Penn State coach</div>"
car[46]="Beginners tip: Make running a habit, even if that means getting out for a few minutes per day.";
car[47]="Sometimes the best runs come on days you didn’t feel like running.";
car[48]="\"The idea that you can’t lose contact with the leaders has cut more throats than it has saved.\"<br><br><div class=\"SigText\">- Arthur Lydiard</div>";
car[49]="Beginners tip: Do a little bit of strength training. Spending just 10 to 15 minutes doing bodyweight workouts in your living room a few times per week will strengthen your core and lower body, which will make running easier and minimize risk of injury.";
car[50]="\"You ran to eat and to avoid being eaten; you ran to find a mate and impress her, and with her you ran off to start a new life together. You had to love running or you wouldn’t live to love anything else.\"<br><br><div class=\"SigText\">- Christopher McDougall, Born to Run: A Hidden Tribe, Superathletes, and the Greatest Race the World Has Never Seen</div>";
car[51]="Reasons to run: Expensive equipment isn’t required.";
car[52]="\"If one can stick to training throughout many long years, then willpower is no longer a problem. It’s raining? That doesn’t matter. I’m tired? That’s beside the point. It’s simply that I have to.\"<br><br><div class=\"SigText\">- Emil Zatopek</div>";
car[53]="Joke Quote:<br><br>\"I’m not sure what just happened but... I just signed up for another race.\"";
car[54]="\"Sometimes, when I walk out onto the track I think, ‘What am I doing here? Why do I put myself through this?’ But that’s when you really get into your focus ... you focus on the race you are going to run.\"<br><br><div class=\"SigText\">- Kelly Holmes</div>";
car[55]="\"My thoughts before a big race are usually pretty simple. I tell myself: ‘Get out of the blocks, run your race, stay relaxed. If you run your race, you’ll win... channel your energy.\"<br><br><div class=\"SigText\">- Carl Lewis</div>";
car[56]="\"The runner is coming to know, or will know if he runs enough... that the universe is the smallest divisible unit.\"<br><br><div class=\"SigText\">- George Sheehan</div>";
car[57]="\"Build up your mileage in gradual increments, but every third or fourth week, drop back in mileage to recover. This will help you avoid your breaking point.\"<br><br><div class=\"SigText\">- Lee Fidler, coach and two-time U.S. Olympic Marathon qualifier</div>";
car[58]="\"In training, don’t be afraid to be an oddball, eccentric, or extremist. Only by daring to go against tradition can new ways of training be learned. The trick is recognizing quickly when a new approach is counterproductive.\"<br><br><div class=\"SigText\">- Benji Durden, 1980 U.S. Olympic marathoner</div>";
car[59]="Beginners tip: Go for distance rather than time - slow it down, be patient, and don’t worry about your pace.";
car[60]="Reasons to run: It lifts your mood.";
car[61]="Joke:<br><br>Q: Did you hear about the marathon runner who ran for three hours but only moved two feet?<br><br>A: (He only had two feet)";
car[62]="\"Fartlek training can help you build strength and endurance, learn race pace, and practice race tactics all in a single workout.\"<br><br><div class=\"SigText\">- Bill Dellinger, former University of Oregon coach and 1964 Olympic 5000 bronze medal winner</div>";
car[63]="You gotta be a beast... even if you are tired.";
car[64]="\"My whole teaching in one sentence is: \"Run slowly, run daily, drink moderately, and don’t eat like a pig.\"<br><br><div class=\"SigText\">- Dr. Ernst van Aaken, renowned German coach</div>";
car[65]="Physical strength will get you to the start line. But mental strength will get you to the finish line.";
car[66]="Joke quote:<br><br>\"Do people running at 6am know about not running at 6am?\"";
car[67]="\"Overly aggressive stretching can actually increase your injury risk.\"<br><br><div class=\"SigText\">- Dr. Ernst van Aaken, renowned German coach</div>";
car[68]="\"You bet your ass I’ll be singing 'Another One Bites The Dust' when I pass other runners on the road or in a race.\"";
car[69]="\"Buy all shoes, both street and running, slightly longer and wider than your bigger foot. Also, avoid pointed shoes. You’ll save yourself needless foot pain.\"<br><br><div class=\"SigText\">- Ted Corbitt</div>";
car[70]="Beginners tip: Keep a training log. Keeping a journal could become your best tool for success.";
car[71]="\"Running 8 to 15 miles per week significantly increases your aerobic capacity, and positively effects many of the coronary risk factors.\"<br><br><div class=\"SigText\">- Dr. Kenneth Cooper, aerobics pioneer</div>";
car[72]="\"I just run. I run in void. Or maybe I should put it the other way: I run in order to acquire a void.\"<br><br><div class=\"SigText\">- Haruki Murakami, What I Talk About When I Talk About Running</div>";
car[73]="Joke:<br><br>Q: Why do runners go jogging early in the morning?<br><br>A: They want to finish before their brain figures out what they are doing.";
car[74]="If it doesn’t challenge you, it doesn’t change you.";
car[75]="Look like a beauty. Train like a beast!";
car[76]="\"I’ve worked hard over the years, I’ve been injured and I’ve worked hard through it, and I’ve made it.\"<br><br><div class=\"SigText\">- Usain Bolt</div>";
car[77]="\"If you don’t have answers to your problems after a 4 hour run, you ain’t getting there.\"<br><br><div class=\"SigText\">- Christopher McDougall</div>";
car[78]="If you have done a strenuous run, have a high protein recovery meal which will help to effectively rebuild your muscles.";
car[79]="\"When I first started running, it was easy. I was young and healthy. Then I quit and had to start again years later when I was neither strong nor healthy. But once my feet hit the pavement, my body took over and every step was a victory.\"<br><br><div class=\"SigText\">- Toni Sorenson</div>";
car[80]="\"The freedom of Cross Country is so primitive. It’s woman vs. nature.\"<br><br><div class=\"SigText\">- Lynn Jennings</div>";
car[81]="Joke quote:<br><br>\"Any idiot can run but it takes a special kind of idiot to run a half marathon.\"";
car[82]="\"If you’re laboring up a steep hill, imagine that a towrope is attached to the center of your chest, pulling you steadily toward the top.\"<br><br><div class=\"SigText\">- Jeff Galloway</div>";
car[83]="\"Their hearts, lost in thought, slowly tick away time. When we pass each other on the road, we listen to the rhythm of each other’s breathing, and sense the way the other person is ticking away the moments.\"<br><br><div class=\"SigText\">- Haruki Murakami, What I Talk About When I Talk About Running</div>";
car[84]="Drink at least 8 oz. of water before heading out to prevent dehydration. If you are going longer than 10k, you might consider taking a water bottle or planning a route that has a water stop along the way. Staying hydrated will stop your legs from cramping.";
car[85]="\"It may seem odd to hear a coach say this, but I think a really great training partner is more important than a coach.\"<br><br><div class=\"SigText\">- Joan Nesbit, coach and world-class runner</div>";
car[86]="\"If you can run six miles on a summer day then you, my friend, are a lethal weapon in the animal kingdom. We can dump heat on the run, but animals can’t pant while they gallop.\"<br><br><div class=\"SigText\">- Christopher McDougall</div>";
car[87]="Courage to start. Strength to endure. Resolve to finish.";
car[88]="Running has taught me that I am capable of so much more than I ever imagined.";
car[89]="\"The ‘talk test’ means running at a pace comfortable enough to converse with a training partner - but not so easy that you could hit the high notes in an Italian opera.\"<br><br><div class=\"SigText\">- Runner’s World editors</div>";
car[90]="\"Marathon training doesn’t have to be a grind. By running for about 30 minutes two times a week, and by gradually increasing the length of a third weekly run-the long run-anyone can finish a marathon.\"<br><br><div class=\"SigText\">- Jeff Galloway</div>";
car[91]="\"There are three reasons I failed. Not enough training. Not enough training. And not enough training.\"<br><br><div class=\"SigText\">- Haruki Murakami, What I Talk About When I Talk About Running</div>";
car[92]="\"I always loved running... it was something you could do by yourself, and under your own power. You could go in any direction, fast or slow as you wanted, fighting the wind if you felt like it, seeking out new sights just on the strength of your feet and the courage of your lungs.\"<br><br><div class=\"SigText\">- Jesse Owens</div>";
car[93]="Happiness is... brand new running shoes.";
car[94]="\"Friedrich Nietzsche got pretty hung up on the notion of human will; really all he needed were some running shoes, lycra and a place in the Berlin Marathon.\"<br><br><div class=\"SigText\">- Phil Hewitt, Keep on Running: The Highs and Lows of a Marathon Addict</div>";
car[95]="\"In running I go by the axiom that my coach Jumbo Elliott of Villanova used: KISS-Keep It Simple, Stupid.\"<br><br><div class=\"SigText\">- Marty Liquori</div>";
car[96]="One run can change your day, many runs can change your life.";
car[97]="\"Our running shoes are really erasers. Every step erases some past failure. Every mile brings us closer to a clean slate. Each foot strike rubs away a word, a look, or an event which led us to believe that success was beyond our grasp.\"<br><br><div class=\"SigText\">- John \"The Penguin\" Bingham</div>";
car[98]="Tough runs don’t last. Tough runners do.";
car[99]="\"People talk about the joy of running - of the endorphins and reaching a Zen-like clarity of mind. This had never happened to me. Mostly, all I thought about when I ran was how much further I had to go before I could stop.\"<br><br><div class=\"SigText\">- Laura Morrigan, Horse of a Different Killer</div>";
car[100]="The race always hurts. Expect it to hurt. You don't train so it doesn’t hurt. You train so you can tolerate it!";
car[101]="Run like there’s a hot guy infront of you and a creepy guy behind you.";
car[102]="Beginners tip: If you are an absolute beginner do lots of walking to start with, alternate running with walking throughout the run for example a minute of walking, followed by a minute of running.";
car[103]="In it for the long run.";
car[104]="\"If you have a bad workout or run a bad race, allow yourself exactly 1 hour to stew about it - then move on.\"<br><br><div class=\"SigText\">- Steve Scott, coach and U.S. record holder in the mile</div>";
car[105]="\"Visualizing perfect running form will help you stay relaxed. Visualize before the race. Then, once you’re in the race, pick out someone who’s looking good and running relaxed. This will help you do the same.\"<br><br><div class=\"SigText\">- Gayle Barron, 1978 Boston Marathon champion</div>";
car[106]="\"I run. Not for PB, PR, course records, medals, recognition. I run for me.\"";
car[107]="I dare you to train for a marathon, and not have it change your life.";
car[108]="\"Do tough workouts that you enjoy. Mile repeats and quarters are more fun for me than fartlek. [\"Fartlek\" is Swedish for variable-paced, up-tempo running.] I feel better about my running when I do the workouts I enjoy and that I know I benefit from.\"<br><br><div class=\"SigText\">- Dan Cloeter, two-time Chicago Marathon winner</div>";
car[109]="Set goals that scare you and excite you at the same time.";
car[110]="Joke:<br><br>Did you hear about the ultra runners who lived in different cities?<br><br>They had a long-distance relationship.";
car[111]="\"Run your own race at an even pace. Consider the course, the temperature, the weather, and most importantly, your current level of fitness.\"<br><br><div class=\"SigText\">- Marty Liquori</div>";
car[112]="Joke:<br><br>Q: How do crazy runners go through the forest?<br><br>A: They take the psycho path.";
car[113]="\"Run like you’re chasing somebody who owes you money.\"<br><br><div class=\"SigText\">- Toni Sorenson</div>";
car[114]="\"To develop your kick, finish each repetition faster than you begin it. For example, if you’re running 6 x 400 meters on the track, start off at a steady, controlled pace, then subtly shift gears in the last 100 or 200 meters.\"<br><br><div class=\"SigText\">- Robert Vaughan, Ph.D., coach and exercise physiologist</div>";
car[115]="Joke:<br><br>*jogs for 8 minutes*<br><br>*doesn’t stop sweating for 14 hours*";
car[116]="\"You can’t be miserable when you’re running. It’s such a simple and pure way to feel alive.\"<br><br><div class=\"SigText\">- Veronica Rossi, Brooke</div>";
car[117]="\"The day after a hard workout, I always train alone. If you run with someone else, there can be a tendency to push harder than you should.\"<br><br><div class=\"SigText\">- Mark Allen, former Ironman champion</div>";
car[118]="\"Some seek the comfort of their therapist’s office, other head to the corner pub and dive into a pint, but I chose running as my therapy.\"<br><br><div class=\"SigText\">- Dean Karnazes, Ultramarathon Man: Confessions of an All-Night Runner</div>";
car[119]="Running is my escape.";
car[120]="\"If you strength train, shelve your routine about a month before your marathon, to help you feel fresh on the big day.\"<br><br><div class=\"SigText\">- Steve Spence, 1991 World Championships Marathon bronze medallist</div>";
car[121]="\"Back off at the first sign of injury. Three to 5 days off is better than missing a month or two. Take regular rest days.\"<br><br><div class=\"SigText\">- Pattisue Plumer, two-time U.S. Olympian</div>";
car[122]="No. your legs aren’t that tired. Yes, you can breathe. Keep going.";
car[123]="Beginners tip:<br><br>Sign up for a fun run / race to give you something to aim for. There is nothing more motivating than having a goal.";
car[124]="You used to hate running. Then you tried it. Then you really tried it. Then you tried harder. Your shorts got shorter. Your runs got longer. Your friends started calling you a runner. Yeah, you. YOU’RE A RUNNER.";
car[125]="\"Winning has nothing to do with racing. Most days don’t have races anyway. Winning is about struggle and effort and optimism, and never, ever, ever giving up.\"<br><br><div class=\"SigText\">- Amby Burfoot, Runner’s Guide to the Meaning of Life</div>";
car[126]="\"After a run, don’t rush back into life. Take a few minutes to walk, stretch, relax, meditate.\"<br><br><div class=\"SigText\">- Runner’s World editors</div>";
car[127]="Run happy. Run grumpy. Run fast. Run slow. Run a little. Run a lot. JUST RUN.";
car[128]="\"[Running] is a hard, simple calculus: Run until you can’t run anymore. Then run some more. Find a new source of energy and will. Then run even faster.\"<br><br><div class=\"SigText\">- Scott Jurek</div>";
car[129]="When you feel like you cannot take another step, that’s when you give it everything you’ve got!";
car[130]="Always find time for the things that make you feel alive... GO RUN!";
car[131]="\"How far can you run? You’ll never know if you don’t move.\"<br><br><div class=\"SigText\">- Toni Sorenson</div>";
car[132]="Joke:<br><br>Q: How do you know when you’ve married a running enthusiast?<br><br>A: When you have more running clothes than regular clothes in your laundry pile.";
car[133]="\"When I go to the Boston Marathon now, I have wet shoulders - women fall into my arms crying. They’re weeping for joy because running has changed their lives. They feel they can do anything.\"<br><br><div class=\"SigText\">- Kathrine Switzer</div>";
car[134]="\"You can’t climb up to the second floor without a ladder. When you set your goal too high and don’t fulfill it, your enthusiasm turns to bitterness. Try for a goal that’s reasonable, and then gradually raise it.\"<br><br><div class=\"SigText\">- Emil Zatopek, four-time Olympic gold medalist from Czechoslavakia</div>";
car[135]="Joke quote:<br><br>Finally tried the whole \"jogging\" thing... there are people who do this every day?? for longer than ten minutes???";
car[136]="\"If you live in the flatlands, you’ll have to be creative about hill training. Deserted highway ramps or parking garages are possibilities, though they pose obvious safety problems. You may want to invest in a treadmill.\"<br><br><div class=\"SigText\">- Bob Glover, runner/author/coach</div>";
car[137]="Joke quote:<br><br>\"Here’s what we’re going to do... we’re going to run 13.1 miles for fun.\"";
car[138]="\"If 15 minutes is all the time I have, I still run. Fifteen minutes of running is better than not running at all.\"<br><br><div class=\"SigText\">- Dr. Duncan Macdonald, former U.S. record holder at 5000 (set when he was in medical school)</div>";
car[139]="When you still haven’t pooped before a race!";
car[140]="\"Run when you can, walk if you have to, crawl if you must; just never give up.\"<br><br><div class=\"SigText\">- Dean Karnazes</div>";
car[141]="Reasons to run: It revs metabolism even while you aren’t doing it.";
car[142]="\"I saw him run for the first time at Wednesday’s training session. Until then, I wasn’t aware Usain Bolt was my running coach\"<br><br><div class=\"SigText\">- Miranda Kenneally, Breathe, Annie, Breathe</div>";
car[143]="\"I double knot my shoe laces. It’s a pain untying your shoes afterward, particularly if you get them wet, but so is stopping in the middle of a race to tie them.\"<br><br><div class=\"SigText\">- Hal Higdon</div>";
car[144]="\"At most, jog easily for 15 minutes before a race. Then stretch your hamstrings, quadriceps, calves, and lower back. With about 15 minutes to go, maybe do a few strides. But no more - you’ll warm up plenty in the early going.\"<br><br><div class=\"SigText\">- Mark Plaatjes, 1993 World Championships marathon winner</div>";
car[145]="Don’t quit. You’re already in pain. You’re already hurt. Get a reward from it.";
car[146]="\"Pick one thing each year that you need to improve, and work on that. It might be improving your diet, getting more sleep, or increasing your mileage. You can’t work on everything at once.\"<br><br><div class=\"SigText\">- Bob Kennedy</div>";
car[147]="\"For me, running is a lifestyle and an art. I’m far more interested in the magic of it than the mechanics.\"<br><br><div class=\"SigText\">- Lorraine Moller</div>";
car[148]="Sometimes all you need is a good run.";
car[149]="\"Kill them with success and bury them with a smile.\"<br><br><div class=\"SigText\">- Usain Bolt</div>";
car[150]="Slow runners make fast runners look good... YOU’RE WELCOME! :)";
car[151]="Joke quote:<br><br>\"My running form could be described as \"drunk woman slowly being chased by no one\"";
car[152]="\"If your morning pulse rate is up 10 or more beats above your average, then you haven’t recovered from the previous day’s training. Take time off or back off until it returns to normal.\"<br><br><div class=\"SigText\">- Dr. George Sheehan</div>";
car[153]="\"If you only ran when you felt like running, you wouldn’t make it very far.\"<br><br><div class=\"SigText\">- Toni Sorenson</div>";
car[154]="\"Think chest / hips / push, or CHP, when it’s time for uphill running. Chest up, hips forward, push strongly off each foot.\"<br><br><div class=\"SigText\">- Jeff Galloway</div>";
car[155]="\"Divide the marathon into thirds. Run the first part with your head, the middle part with your personality, and the last part with your heart.\"<br><br><div class=\"SigText\">- Mike Fanelli, runner and coach</div>";
car[156]="\"When you run, every step you take leaves your weaker self behind and brings you one step closer to the strongest person you can be.\"<br><br><div class=\"SigText\">- Toni Sorenson</div>";
car[157]="\"You find out by trial and error what the optimum level of training is. If I found I was training too hard, I would drop back for a day or so. I didn’t run for 5 days before the sub-4.\"<br><br><div class=\"SigText\">- Toni Sorenson</div>";
car[158]="Reasons to run: Solo runs provide time for self discovery.";
car[159]="\"But you can’t muscle through a five-hour run that way; you have to relax into it like easing your body into a hot bath, until it no longer resists the shock and begins to enjoy it.\"<br><br><div class=\"SigText\">- Christopher McDougall, Born to Run: A Hidden Tribe, Superathletes, and the Greatest Race the World Has Never Seen</div>";
car[160]="\"We wouldn’t be alive without love we wouldn’t have survived without running maybe we shouldn’t be surprised that getting better at one could make you better at the other.\"<br><br><div class=\"SigText\">- Christopher McDougall, Born to Run: A Hidden Tribe, Superathletes, and the Greatest Race the World Has Never Seen</div>";
car[161]="\"During long, slow distance training, you should think of yourself as a thoroughbred disguised as a plow horse. No need to give yourself away by running fast.\"<br><br><div class=\"SigText\">- Marty Liquori, running commentator and former world-class miler</div>";
car[162]="There’s magic in misery, just ask any runner.";
car[163]="\"Like cross-training, ‘cross-eating’ adds needed variety to your diet-and life. Expand your nutritional repertoire by trying one new food each week.\"<br><br><div class=\"SigText\">- -Liz Applegate, Ph.D.</div>";
car[164]="If you see me collapse, pause my watch.";
car[165]="\"The primary reason to have a coach is to have someone who says: ‘Hey, you’re looking good today!’<br><br><div class=\"SigText\">- Jack Daniels, Ph.D.</div>";
car[166]="It hurts now, but one day it will be your warm up.";
car[167]="\"The long run puts the tiger in the cat.\"<br><br><div class=\"SigText\">- Bill Squires, marathon coach</div>";
car[168]="Don’t give up because you had a bad run. Forgive yourself and do better tomorrow.";
car[169]="Joke quote:<br><br>I run because \"OMG you look amazing!\" never gets old.";
car[170]="Joke quote:<br><br>\"What the f**k are we doing\" - my legs during recreational jogging.";
car[171]="\"Fitness has to be fun. If it isn’t, there will be no fitness. Play is the process. Fitness is merely the product.\"<br><br><div class=\"SigText\">- Dr. George Sheehan</div>";
car[172]="\"If I am still standing at the end of the race, hit me with a board and knock me down, because that means I didn’t run hard enough.\"<br><br><div class=\"SigText\">- Steve Jones</div>";
car[173]="Joke quote:<br><br>I hate when I’m running on the treadmill for half an hour and look down to see it’s been 4 minutes.";
car[174]="Beginners tip: Mix in cross training to supplement your running, such as cycling or a gym class.";
car[175]="\"To be effective over the last 6 miles of a marathon, one must harbor some sort of emotional as well as physical reserves.\"<br><br><div class=\"SigText\">- Kenny Moore, writer and two-time U.S. Olympic marathoner</div>";
car[176]="\"I will... just watch me!\"";
car[177]="\"We knew not where we were going. We only knew that we must run, run to the end of the world, run to the end of our days.\"<br><br><div class=\"SigText\">- Ayn Rand</div>";
car[178]="\"When I’m training for a marathon, I soak in a hot tub every day, and get a weekly massage.\"<br><br><div class=\"SigText\">- Anne Marie Lauck, two-time Olympian</div>";
car[179]="\"Finish: Even if you run a slower than expected time, you succeed in any marathon when you finish.\"<br><br><div class=\"SigText\">- Hal Higdon, 4:09:43: Boston 2013</div>";
car[180]="\"All I do is keep on running in my own cozy, homemade void, my own nostalgic silence. And this is a pretty wonderful thing. No matter what anybody else says.\"<br><br><div class=\"SigText\">- Haruki Murakami, What I Talk About When I Talk About Running</div>";
car[181]="\"When you try a new type of training, think like a beginner. Just because you can run 20 miles every Sunday doesn’t mean you can survive 10 x 400 meters on the track at a fast pace.\"<br><br><div class=\"SigText\">- Jack Daniels, Ph.D.</div>";
car[182]="\"Beginners tip: Set small, achievable goals. Break down your aspirations into daily, weekly, and monthly goals.\"<br><br><div class=\"SigText\">- Usain Bolt</div>";
car[183]="\"There is something magical about running; after a certain distance, it transcends the body. Then a bit further, it transcends the mind. A bit further yet, and what you have before you, laid bare, is the soul.\"<br><br><div class=\"SigText\">- Kristin Armstrong</div>";
car[184]="\"Runners don’t quit. We fade; we \"hit the wall\"; we’re sometimes reduced to a walk. But we keep on.\"<br><br><div class=\"SigText\">- Amby Burfoot</div>";
car[185]="\"The advantage of running ‘hills’ on a treadmill is you can go up without pounding down the other side.\"<br><br><div class=\"SigText\">- Ken Sparks, Ph.D.</div>";
car[186]="Running is like coffee... much nicer when I’ve had one.";
car[187]="\"Passing competitors always gives you a lift. It probably has a physical effect, too, because you get a surge of adrenaline.\"<br><br><div class=\"SigText\">- Libbie Hickman, world-class marathoner</div>";
car[188]="\"The difference between a jogger and a runner is a race-entry blank.\"<br><br><div class=\"SigText\">- Dr. George Sheehan</div>";
car[189]="\"Don’t think about the start of the race.\"<br><br><div class=\"SigText\">- Usain Bolt</div>";
car[190]="Beginners tip: Build mileage gradually.";
car[191]="\"Slip in behind someone running a similar pace and, yes, draft. It’s not illegal. It’s not even poor form. On the contrary, it’s just plain smart.\"<br><br><div class=\"SigText\">- Priscilla Welch, former British Olympian and 1987 New York City Marathon champ</div>";
car[192]="\"We wrote our workout schedules in 3-week blocks. My coach and I knew what my immediate goal was-what I was trying to accomplish in the next 3 weeks. But in the back of my mind was the ultimate goal: what I wanted to do months away.\"<br><br><div class=\"SigText\">- Bob Kennedy</div>";
car[193]="\"Racing is an escape from society. From symbols of status, and self-perception. A chance to just be. For everyone to just be, with each other.\"<br><br><div class=\"SigText\">- Erin Beresini, Off Course: Inside the Mad, Muddy World of Obstacle Course Racing</div>";
car[194]="\"Spend at least $60. A good pair of running shoes should last you 400 to 500 miles and is one of the most critical purchases you will make.\"<br><br><div class=\"SigText\">- John Hanc, author of The Essential Runner</div>";
car[195]="No matter how slow you go you are still lapping everyone on the couch.";
car[196]="\"Forget the glass slippers.. this princess wears running shoes.\"";
car[197]="Bad weather is not an excuse... IT’S COMPETITION!";
car[198]="When your legs can’t run anymore... RUN WITH YOUR HEART!";
car[199]="I run. I’m slower than a herd of turtles stampeding through peanut butter. But I run.";
car[200]="The hard part isn’t getting your body in shape. The hard part is getting your mind in shape.";
car[201]="\"It’s better to run too slow at the start than too fast and get into oxygen debt, which is what 99.9 percent of runners do. You have to learn pace.\"<br><br><div class=\"SigText\">- Bill Bowerman, renowned University of Oregon coach</div>";
car[202]="\"I know what to do and I go and execute.\"<br><br><div class=\"SigText\">- Usain Bolt</div>";
car[203]="\"Midday running provides a triple benefit: daylight, a break from the workday, and a chance to avoid eating a heavy lunch.\"<br><br><div class=\"SigText\">- Joe Henderson, runner/writer</div>";
car[204]="\"When going down, I lean with the hill. I know I’m doing it right if I feel like I’m going to fall on my face.\"<br><br><div class=\"SigText\">- Ed Eyestone, RW columnist, coach, and two-time U.S. Olympic marathoner</div>";
car[205]="\"Brainstorm your training goals first, then write them down. Do this in pencil, so you can change some specifics when reality sets in.\"<br><br><div class=\"SigText\">- Jeff Galloway</div>";
car[206]="\I could feel my anger dissipating as the miles went by - you can’t run and stay mad!\"<br><br><div class=\"SigText\">- Kathrine Switzer, Marathon Woman: Running the Race to Revolutionize Women’s Sports</div>";
car[207]="\"When you run through life, life runs through you\"<br><br><div class=\"SigText\">- Toni Sorenson</div>";
car[208]="\"Running cleared the day’s cobwebs from my mind and focused my thinking, and gave me time and space to sort out anything that was bothering me, or to detach and think of nothing at all.\"<br><br><div class=\"SigText\">- Jeff Horowitz, My First 100 Marathons: 2,260 Miles with an Obsessive Runner</div>";
car[209]="\"Whether one shall run on his heels or his toes is hardly worth discussing. The main thing in distance running is endurance - and how to get it.\"<br><br><div class=\"SigText\">- Clarence DeMar, seven-time Boston Marathon champion and U.S. Olympic marathoner";
car[210]="Not training to be skinny... training to be badass!";
car[211]="Beginners tip: Join a running group. Though you should do some solo runs, there are many benefits to running with a group.";
car[212]="Excuses don’t burn calories.";
car[213]="Joke:<br><br>Q: What do runners do when they forget something?<br><br>A: They jog their memory.";
car[214]="Running reminds you that even in your weakest moments... YOU ARE STRONG!";
car[215]="Beginners tip: Get fitted for trainers at a speciality shop. The right pair of running shoes will mean a more comfortable run and lower risk of injury.";
car[216]="\"That’s the funny thing about running. The deceptive thing about it. It may seem mindless, but its really mental. If the minds strong, the body acts weak, even if its not.\"<br><br><div class=\"SigText\">- Wendelin Van Draanen, The Running Dream</div>";
car[217]="\"Running is not just exercise for your body, it tends to get your whole life in better shape.\"<br><br><div class=\"SigText\">- Toni Sorenson</div>";
car[218]="\"Your body is always trying to tell you where you are. Beware when you become tired and listless, when you lose interest in workouts and approach them as a chore rather than a pleasure.\"<br><br><div class=\"SigText\">- Dr. George Sheehan</div>";
car[219]="Running in the rain... exercise, therapy, and a shower at the same time.";
car[220]="Joke:<br><br>Q: How do you know your a dedicated runner?<br><br>A: When your treadmill has more miles on it than your car.";
car[221]="Runderful (adjective): How you feel the minute after you finish your run.";
car[222]="\"So-called ‘junk miles’ - those slow miles done on easy days or during warmups do count. They burn calories as effectively as fast miles; it just takes longer. Regardless of pace, each mile you run burns about 100 calories.\"<br><br><div class=\"SigText\">- Hal Higdon</div>";
car[223]="\"Those runners who hit their second wind know find something most of the world never discovers.\"<br><br><div class=\"SigText\">- Toni Sorenson</div>";
car[224]="Track the mileage in your shoes. At about 300 miles, mid-soles can become too compressed to return to their original shape between runs, and your feet and legs will begin to notice. Be sure to replace shoes regularly.";
car[225]="\"Before you do your long run, place containers of sports drink out on your course, even if you have to bury them.\"<br><br><div class=\"SigText\">- Runner’s World editors</div>";
car[226]="\"I include iron with vitamin C in my diet to prevent anemia. Without it, I wouldn’t have the energy I need to train.\"<br><br><div class=\"SigText\">- Joy Smith, 2:34 marathoner</div>"
car[227]="\"Blaming the running injury epidemic on big, bad Nike seems too easy - but that’s okay, because it’s largely their fault.\"<br><br><div class=\"SigText\">- Christopher McDougall, Born to Run: A Hidden Tribe, Superathletes, and the Greatest Race the World Has Never Seen</div>";
car[228]="Something only a runner would understand... the first mile is a liar, don’t even trust it!";
car[229]="Running is a mental sport. We are all insane.";
car[230]="\"I’ve always found it effective in a race to make a move just before the crest of a hill. You get away just a little, and you’re gone before they get over the top.\"<br><br><div class=\"SigText\">- John Treacy, two-time World Cross-Country champion from Ireland</div>";
car[231]="You won’t get fat eating one bad meal and you won’t get lean eating one healthy meal. You are what you repeatedly do. Maintaining a healthy lifestyle is a lifestyle not a destination.";
car[232]="\"In an era when man can no longer dash out of his cave and slay a mammoth, he simply slips on his lycra and goes for a run.\"<br><br><div class=\"SigText\">- Phil Hewitt, Keep on Running: The Highs and Lows of a Marathon Addict</div>";
car[233]="\"Athletes need to enjoy their training. They don’t enjoy going down to the track with a coach making them do repetitions until they’re exhausted. From enjoyment comes the will to win.\"<br><br><div class=\"SigText\">- Arthur Lydiard</div>";
car[234]="A little progress each day adds up to big results.";
car[235]="\"It is not how fast or how far, but how often you run that makes you a real runner.\"<br><br><div class=\"SigText\">- Toni Sorenson</div>";
car[236]="\"The footing was really atrocious. I loved it. I really like Cross Country; you’re one with the mud.\"<br><br><div class=\"SigText\">- Lynn Jennings</div>";
car[237]="Focus on your goal, don’t look in any direction but ahead.";
car[238]="\"Try some light jogging or walking before you stretch, or stretch after you run. Stretching ‘cold’ muscles can cause more harm than good.\"<br><br><div class=\"SigText\">- Runner’s World editors</div>";
car[239]="Joke:<br><br>I’m thinking of running a marathon. Well, I’m thinking of TRAINING for a marathon. Okay, I just want to carboload.";
car[240]="\"Vary your training, your running partners, and your environment. Only your imagination limits the ways you can spice up your running routine.\"<br><br><div class=\"SigText\">- Bob Glover</div>";
car[241]="\"Vary your training, your running partners, and your environment. Only your imagination limits the ways you can spice up your running routine.\"<br><br><div class=\"SigText\">- Bob Glover</div>";
car[242]="\"Running is the greatest metaphor for life, because you get out of it what you put into it.\"<br><br><div class=\"SigText\">- Oprah Winfrey</div>";
car[243]="Joke quote:<br><br>\"That awkward moment running near a friends house when you want to text them 'hey, can I poop in your bathroom real quick?'\"";
car[244]="\"How to run an ultramarathon? Puff out your chest, put one foot in front of the other, and don’t stop till you cross the finish line.\"<br><br><div class=\"SigText\">- Dean Karnazes, Ultramarathon Man: Confessions of an All-Night Runner</div>";
car[245]="\"We run when we’re scared, we run when we’re ecstatic, we run away from our problems and run around for a good time.\"<br><br><div class=\"SigText\">- Christopher McDougall, Born to Run: A Hidden Tribe, Superathletes, and the Greatest Race the World Has Never Seen</div>";
car[246]="\"Running is a simple activity. Just lace up your shoes and go, one step at a time, like each breath.\"<br><br><div class=\"SigText\">- Adharanand Finn, Running with the Kenyans: Passion, Adventure, and the Secrets of the Fastest People on Earth</div>";
car[247]="\"The difference between the impossible and the possible lies in determination.\"<br><br><div class=\"SigText\">- Usain Bolt</div>";
car[248]="Yes, you’re busy, we all are. Don’t be a drama queen... JUST DO IT!";
car[249]="Rungry: When you are so hungry from your long run that you must eat everything.";
car[250]="\"In marathon training, 3 hours slow is better than 2 hours fast.\"<br><br><div class=\"SigText\">- Pete Gavuzzi, coach of four-time Boston Marathon champ Gerard Cote</div>";
car[251]="Beginners tip: Don’t even worry about pace or mileage. Just focus on consistency. You’ll soon notice how much easier it will start to feel once you’ve been doing it regularly for a few weeks.";
car[252]="Sometimes... all you need is a good run.";
car[253]="\"If you run 30 miles a week, then about 7 of those - or approximately one quarter should be quality miles. Quality miles will boost your aerobic capacity.\"<br><br><div class=\"SigText\">- Owen Anderson, Ph.D., running writer</div>";
car[254]="\"Pain is inevitable. Suffering is optional.\"<br><br><div class=\"SigText\">- Haruki Murakami</div>";
car[255]="Rise and run.";
car[256]="Beginners tip: Don’t dread taking walk breaks. In fact, slowing down can actually build strength and endurance to benefit your running.";
car[257]="\"I work hard, and I do good, and I’m going to enjoy myself. I’m not going to let you restrict me.\"<br><br><div class=\"SigText\">- Usain Bolt</div>";
car[258]="\"The marathon will humble you. But the truth is, sometimes it will do more than humble you. Sometimes it will break your heart.\"<br><br><div class=\"SigText\">- Bill Rodgers, Marathon Man: My 26.2-Mile Journey from Unknown Grad Student to the Top of the Running World</div>";
car[259]="\"There are no standards and no possible victories except the joy you are living while dancing your run. You are not running for some future reward - the real reward is now!\"<br><br><div class=\"SigText\">- Fred Rohe, The Zen of Running</div>";
car[260]="Joke:<br><br>Me: Can’t go running with you, all my workout clothes are dirty.<br><br>Friend: Oh nice, been exercising?<br><br>Me: No, pasta sauce.";
car[261]="\"When running, let your jaw hang loose, don’t bunch up your shoulders close to your ears, and occasionally shake out your hands and arms to stay relaxed.\"<br><br><div class=\"SigText\">- Dave Martin, Ph.D., exercise physiologist</div>";
car[262]="\"Energy bars are good portable food for runners. Look for bars with 4 grams of fat or fewer per 230 calories. Fat slows down digestion.\"<br><br><div class=\"SigText\">- Liz Applegate, Ph.D., sports nutritionist</div>";
car[263]="\"Thanks to the race-day adrenaline rush, any pace will feel easier than normal. So make a conscious effort to hold back in the early miles.”\"<br><br><div class=\"SigText\">- Lorraine Moller</div>";
car[264]="\"Success breeds success on a marathon route. If you can prove to yourself that you are doing well, then invariably you will do even better.\"<br><br><div class=\"SigText\">- Phil Hewitt, Keep on Running: The Highs and Lows of a Marathon Addict</div>";
car[265]="\"Never run more than 3 hours straight in training, whether your marathon best is 2:42 or 4:24.\"<br><br><div class=\"SigText\">- Ed Eyestone</div>";
car[266]="If you are a runner. It doesn’t matter how fast or how far. It doesn’t matter if today is your first day or if you’ve been running for twenty years. There is no test to pass, no license to earn, no membership card to get. YOU JUST RUN.";
car[267]="\"This is your first marathon. Possibly, you’ll want it to be your last. Focus on future races draws energy from the one in front of you. Like the mileage that comprises them, train for marathons one at a time.\"<br><br><div class=\"SigText\">- Gina Greenlee, The Whole Person Guide to Your First Marathon: A Mind Body Spirit Companion</div>";
car[268]="\"There are many challenges to long distance running, but one of the greatest is the question of where to put one’s house keys.\"<br><br><div class=\"SigText\">- Gabrielle Zevin, The Storied Life of A.J. Fikry</div>";
car[269]="\"I’ll be happy if running and I can grow old together.\"<br><br><div class=\"SigText\">- Haruki Murakami, What I Talk About When I Talk About Running</div>";
car[270]="\"Running is a lot like life. Only 10 percent of it is exciting. 90 percent of it is slog and drudge.\"<br><br><div class=\"SigText\">- David Bedford</div>";
car[272]="No pain no champagne.";
car[273]="\"'You don’t run,’ he corrected me. ‘But you’re more than able.’ There was no shadow of doubt in his voice. Hearing it from someone else made me realize: there was nothing stopping me from running but me.\"<br><br><div class=\"SigText\">- Alexandra Heminsley, Running Like a Girl</div>";
car[274]="Every one of your dreams is patiently sitting right outside of your comfort zone.";
car[275]="Not everyone will understand you are up before the sun or out running in the cold. That’s OK, you’re here to live your life, not to make everyone understand.";
car[276]="\"Three half-mile repeats on the track at 5k race pace with a short recovery jog in between shouldn’t scare anyone away - and it will improve your speed.\"<br><br><div class=\"SigText\">- Frank Shorter</div>";
car[277]="\"And, finally, I run because there’s no better way to see the sun rise and set.”\"<br><br><div class=\"SigText\">- Amby Burfoot</div>";
car[278]="I’ve got 99 problems but I’m going running to ignore them all for an hour.";
car[279]="Do something today that you will be proud of tomorrow.";
car[280]="Joke:<br><br>Q: What do you get when you run behind a car?<br><br>A: Exhausted.";
car[281]="I run because I can. When I get tired, I remember those who can’t run, what they would give to have this simple gift I take for granted, and I run harder for them. I know they would do the same for me.";
car[283]="\The essential thing is to run, period! And to do it for a long time and consistently and then everything will take care of itself.\"<br><br><div class=\"SigText\">- Bernd Heinrich</div>";
car[284]="\"If you can’t run fast, run slow. If you can’t run slow, walk. If you can’t walk, crawl. All that matters is that you don’t stop moving.\"<br><br><div class=\"SigText\">- Toni Sorenson</div>";
car[285]="You will want to stop... DON’T!";
car[286]="Beginners tip: Use a Couch to 5K app to ease yourself into running. The Couch to 5K app will have you ready to run 3.1 miles after nine weeks of 20 to 30 minute workouts that alternate walking and running three times per week.";
car[287]="\"When I’m running, I settle my own disputes and comfort my ailing emotions. I don’t know why, but answers seem more obvious and problems less troublesome when I’m in motion.\"<br><br><div class=\"SigText\">- Dave Griffin</div>";
car[288]="\"If you don’t think you were born to run you’re not only denying history. You’re denying who you are.\"<br><br><div class=\"SigText\">- Christopher McDougall, Born to Run: A Hidden Tribe, Superathletes, and the Greatest Race the World Has Never Seen</div>";
car[289]="Unless you puke, faint or die... KEEP GOING!";
car[290]="\"The key step between a great training program and a great race is a great taper. Your last long training run before a marathon should come 3 weeks before the race - not 2.\"<br><br><div class=\"SigText\">- Pete Pfitzinger, two-time U.S. Olympic marathoner</div>";
car[291]="Train insane or remain the same.";
car[292]="\"In a sprint, if you don’t have perfect form, you’re doomed. The ultra distance forgives injury, fatigue, bad form, and illness. A bear with determination will defeat a dreamy gazelle every time.\"<br><br><div class=\"SigText\">- Scott Jurek, Eat and Run: My Unlikely Journey to Ultramarathon Greatness</div>";
car[293]="Happiness is... sweet exhaustion after a hard run.";
car[294]="\"When it’s pouring rain and you’re bowling along through the wet, there’s satisfaction in knowing you’re out there and the others aren’t.\"<br><br><div class=\"SigText\">- Peter Snell</div>";
car[295]="It’s not bragging when I tell you how many miles I ran today. It’s so you don’t judge when I devour the whole bag of chips.";
car[296]="There is magic in misery. just ask a runner.";
car[297]="The truth is you can always run faster, but sometimes the truth hurts.";
car[298]="The act of getting strong doesn’t start in a gym, it starts in your head.";
car[299]="\"Some sessions are stars and some sessions are stones, but in the end they are all rocks and we build upon them.\"<br><br><div class=\"SigText\">- Chrissie Wellington, A Life Without Limits: A World Champion’s Journey</div>";
car[300]="Stop asking what I’m doing this weekend. Running. I’m running this weekend, next weekend, forever.";
car[301]="\"Occasionally pick up speed for 2 minutes tops, then settle back into your former pace. Sometimes this is all you need to snap out of a mental and physical funk. Pick a downhill stretch if you can, and really lengthen your stride.\"<br><br><div class=\"SigText\">- Mark Plaatjes</div>";
car[302]="Your only limit is you.";
car[303]="\"But anybody who steps into the lane beside you is the biggest competition because they made it to the finals.\"<br><br><div class=\"SigText\">- Usain Bolt</div>";
car[304]="\"I don’t wear a watch during my long runs. That way I’m not tempted to compare my time from week to week.\"<br><br><div class=\"SigText\">- Lynn Jennings, three-time World Cross-Country champion</div>";
car[305]="Joke:<br><br>How can you tell is someone ran a marathon?<br><br>Don’t worry, they’ll tell you.";
car[306]="\"Not all races are run on a track. And not all finish lines are marked by ticker tape.\"<br><br><div class=\"SigText\">- Toni Sorenson</div>";
car[307]="\"Running is about finding your inner peace, and so is a life well lived.\"<br><br><div class=\"SigText\">- Dean Karnazes</div>";
car[308]="\"Quality counts, if you want to stay fast. Don’t do all your workouts in the comfort zone.\"<br><br><div class=\"SigText\">- Ken Sparks, Ph.D.</div>";
car[310]="\"Any idiot can train himself into the ground; the trick is doing the training that makes you gradually stronger.\"<br><br><div class=\"SigText\">- Keith Brantly, U.S. Olympic marathoner</div>";
car[311]="\"We are different, in essence, from other men. If you want to win something, run 100 meters. If you want to experience something, run a marathon.\"<br><br><div class=\"SigText\">- Emil Zatopek</div>";
car[312]="\"There is something magical about running; after a certain distance, it transcends the body. Then a bit further, it transcends the mind. A bit further yet, and what you have before you, laid bare, is the soul.\"<br><br><div class=\"SigText\">- Kristin Armstrong</div>";
car[313]="If you eat a large meal before a run, wait at least three hours before you head out. Almost nothing you eat immediately before a run will digest enough to give you energy during your run. If you do have to eat, choose something your system can easily absorb, such as a banana, a few spoonfuls of peanut butter, of a handful of dried fruit.";
car[314]="Off to run I go... to lose my mind and find my soul.";
car[315]="\"You have to forget your last marathon before you try another. Your mind can’t know what’s coming.\"<br><br><div class=\"SigText\">- Frank Shorter</div>";
car[316]="OMG... IT’S RACE DAY!";
car[317]="Running is not about being someone else, it’s about being better than you used to be.";
car[318]="Reasons to run: It’s a top calorie burning exercise.";
car[319]="Sweat is just fat crying.";
car[320]="Joke quote:<br><br>\"Woke up in running clothes. really admire drunk me and her ambitions.\"";
car[322]="\"Keep working on mental attitude. You have to fight that supposedly rational voice that says: ‘I’m 50 years old, and I don’t have to be doing this anymore.’\"<br><br><div class=\"SigText\">- Ken Sparks, Ph.D.</div>";
car[323]="\"Day to day consistency is more important than big mileage. Then you’re never shot the next day.\"<br><br><div class=\"SigText\">- John Campbell, former masters running star from New Zealand</div>";
car[324]="\"The biggest mistake that new runners make is that they tend to think in mile increments - 1 mile, 2 miles, 3 miles. Beginning runners need to think in minutes, not miles.\"<br><br><div class=\"SigText\">- Budd Coates</div>";
car[325]="Don’t let success go to your head and failure go to your heart.";
car[326]="\"What I’ve learned from running is that the time to push hard is when you’re hurting like crazy and you want to give up. Success is often just around the corner.\"<br><br><div class=\"SigText\">- James Dyson</div>";
car[327]="\"Don’t clench your fists in a white-knuckle grip. Instead, run with a cupped hand, thumbs resting on the fingers, as if you were protecting an egg in each palm.\"<br><br><div class=\"SigText\">- Runner’s World editors</div>";
car[328]="Reasons to run: It’s awesome for your social life.";
car[329]="Joke quote:<br><br>[friend is telling me about running a marathon] *raises hand* \"So you like did this on purpose?\"";
car[330]="\"I believe in using races as motivators. It’s hard to keep on an exercise program if you don’t have a significant goal in sight.\"<br><br><div class=\"SigText\">- Bob Greene, personal trainer of Oprah Winfrey</div>";
car[331]="I became a great runner because if you’re a kid in Leeds and your name is Sebastian you’ve got to become a great runner.\"<br><br><div class=\"SigText\">- Sebastian Coe</div>";
car[332]="\"Running, the music flew into him, became the wind that pushed back his hair and the slap of his own feet on the pavement.\"<br><br><div class=\"SigText\">- Ann Patchett, Bel Canto</div>";
car[333]="\"Your body will argue that there is no justifiable reason to continue. Your only recourse is to call on your spirit, which fortunately functions independently of logic.\"<br><br><div class=\"SigText\">- Tim Noakes, Lore of Running</div>";
car[334]="Beginners tip: Think of days off as part of your training. To get stronger and fitter and become a better runner, you need to recover from your workouts so you can get back out there and crush it again tomorrow or the next day.";
car[335]="Breathe it in. Run it out.";
car[336]="Joke quote:<br><br>\"I run because it’s good for me. Also, because I like to eat and drink A LOT!\"";
car[337]="\"I was pushed by myself because I have my own rule, and that is that every day I run faster, and try harder.\"<br><br><div class=\"SigText\"> - Wilson Kipketer after being asked is the $50,000 prize on offer tempted him to break the world record.</div>";
car[338]="\"I often hear someone say I’m not a real runner. We are all runners, some just run faster than others. I never met a fake runner.\"<br><br><div class=\"SigText\">- Bart Yasso</div>";
car[339]="\"As every runner knows, running is about more than just putting one foot in front of the other; it is about our lifestyle and who we are.\"<br><br><div class=\"SigText\">- Joan Benoit Samuelson</div>";
car[340]="\"Hills are the only beneficial type of resistance training for a runner.\"<br><br><div class=\"SigText\">- Arthur Lydiard, Olympic coach from New Zealand</div>";
car[341]="\"Rather than going into a marathon with just one goal - such as finishing in a very specific time-develop a range of goals so that you increase your chances of success.\"<br><br><div class=\"SigText\">- Jerry Lynch, Ph.D., marathoner and author of The Total Runner</div>";
car[342]="\"Never underestimate the value of a good training partner, even if it’s your dog. Training allies will get you out the door on those days when exercise might otherwise be reduced to a finger on the remote control button.\"<br><br><div class=\"SigText\">- Runner’s World editors</div>";
car[343]="It doesn’t get easier... you get stronger!";
car[344]="Begin your runs with a very relaxed and easy stride - not too fast. Increase your pace slowly, until you’re running at your desired level. If you start off too fast you risk running out of gas early in your run, and you’ll feel more soreness in your legs afterwards.";
car[345]="\"I’m never going to run this again.\"<br><br><div class=\"SigText\">- Grete Waitz, after the first of nine NYC Marathons.</div>";
car[346]="Beginners tip: Use an app such as Strava or RunKeeper to track your runs so that you can see your progress and make notes about your workouts.";
car[347]="Runners high (Noun): An addictive side effect of running, a euphoric state of bliss that may be the reason that runners run.";
car[348]="\"Running against traffic allows the runner to be in command. Anyone who is alert and agile should be able to stay alive.\"<br><br><div class=\"SigText\">- Dr. George Sheehan</div>";
car[349]="\"Every race proves a new opportunity to educate myself about what it means to be a runner and what it means to run.\"<br><br><div class=\"SigText\">- Jill Grunenwald, Running with a Police Escort: Tales from the Back of the Pack</div>";
car[350]="Don’t put in half of the effort unless you’re ok with half of the results.";
car[351]="\"It is never wise to run any race but your own.\"<br><br><div class=\"SigText\">- Tim Fargo</div>";
car[352]="\"Expect to put in 6 to 10 successful track workouts before you begin to see some payoff in your races.\"<br><br><div class=\"SigText\">- Marc Bloom</div>";
car[353]="\"During the hard training phase, never be afraid to take a day off. If your legs are feeling unduly stiff and sore, rest. If you’re at all sluggish, rest. Whenever you’re in doubt, rest.\"<br><br><div class=\"SigText\">- Bruce Fordyce, nine-time Comrades Marathon champion</div>";
car[354]="You don’t get better at running hills... by walking them.";
car[355]="\"Running would help with the weight, but the weight did not help with running.\"<br><br><div class=\"SigText\">- Alexandra Heminsley, Running Like a Girl</div>";
car[356]="\"Then, I started running. And everything was as good as it could be.\"<br><br><div class=\"SigText\">- Stephen Chbosky</div>";
car[357]="\"The reason we race isn’t so much to beat each other, he understood, but to be with each other.\"<br><br><div class=\"SigText\">- Christopher McDougall, Born to Run: A Hidden Tribe, Superathletes, and the Greatest Race the World Has Never Seen</div>";
car[358]="\"If you’re on the treadmill next to me, the answer is YES, we are racing.\"<br><br><div class=\"SigText\">- Loves Running</div>";
car[359]="\"I never go into a race expecting to win, but I do go in expecting to fight.\"<br><br><div class=\"SigText\">- Chrissie Wellington</div>";
car[360]="\"Running is a big question mark that’s there each and every day. It asks you, 'Are you going to be a wimp or are you going to be strong today?'\"<br><br><div class=\"SigText\">- Peter Maher</div>";
car[361]="\"For every runner who tours the world running marathons, there are thousands who run to hear the leaves and listen to the rain, and look to the day when it is suddenly as easy as a bird in flight.\"<br><br><div class=\"SigText\">- George Sheehan</div>";
car[362]="\"Running is a brutal and emotional sport. It’s also a simple, primal sport. As humans, on a most basic level, we get hungry, we sleep, we yearn for love, we run.\"<br><br><div class=\"SigText\">- Adharanand Finn, Running with the Kenyans: Passion, Adventure, and the Secrets of the Fastest People on Earth</div>";
car[363]="\"Believe that you can run farther or faster. Believe that you’re young enough, old enough, strong enough, and so on to accomplish everything you want to do. Don’t let worn out beliefs stop you from moving beyond yourself.\"<br><br><div class=\"SigText\">- John Bingham</div>";
car[364]="\"Today, I run for pure, absolute joy.\"<br><br><div class=\"SigText\">- Lopez Lomong</div>";
car[365]="\"...be as fast as Usain Bolt, the winner is the winner, even if he crawls like a crab, his destiny is unshakable.\"<br><br><div class=\"SigText\">- Michael Bassey Johnson</div>";
car[366]="\"So they went running together, silent, toward the vast wastes of snow where no living thing but they two moved under the stars of night.\"<br><br><div class=\"SigText\">- Clemence Housman, The Were-Wolf</div>";
car[367]="It hurts now, but one day it will be your warm up.";